EXPECTED_SCHEMAS = {
  "leagues": [
    "league_id",
    "name",
    "country",
    "country_id",
    "icon_url",
    "cl_spot",
    "uel_spot",
    "relegation_spot",
  ],
  "matches": [
    "match_id",
    "season_id",
    "league_id",
    "matchday",
    "home_team_id",
    "away_team_id",
    "winner",
    "utc_date",
  ],
  "scores": [
    "score_id",
    "match_id",
    "full_time_home",
    "full_time_away",
    "half_time_home",
    "half_time_away",
  ],
  "standings": [
    "standing_id",
    "season_id",
    "league_id",
    "position",
    "team_id",
    "played_games",
    "won",
    "draw",
    "lost",
    "points",
    "goals_for",
    "goals_against",
    "goal_difference",
    "form",
  ],
  "teams": [
    "team_id",
    "name",
    "founded_year",
    "stadium_id",
    "league_id",
    "coach_id",
    "cresturl",
  ],
}